swiftmailer:
    transport: gmail
    auth_mode: login
    port: 465
    encryption: ssl
    host: smtp.gmail.com
    username:  solidev.3a18@gmail.com
    password:  NEXUS123.
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']